### ISSUE TITLE
Mooprofile block stops Moodle upgrade from 2.6 to 3.0

### ISSUE THREAD

**Issue by tabitharoder** [satrun77/MooProfile-Moodle-Plugin#2]
We are upgrading our Moodle application to 3.0 and have noticed that MooProfile block is not behaving as expected.
When we are doing the upgrade (from 2.6) it gives an error message and stops the upgrade process and stops other plugins being installed. 
Screenshot attached. 

![mooprofile_upgrade_screenshot](https://cloud.githubusercontent.com/assets/16788558/12437308/9c3d9dce-bf81-11e5-91e5-a66a62231abc.png)

**Comment by satrun77** [comment]
I have fixed the error. 

Plugin not updated in moodle.org yet. Also, not tested.

You can test the plugin by downloaded the code from https://github.com/satrun77/MooProfile-Moodle-Plugin/archive/master.zip

**Comment by tabitharoder** [comment]
This works for us. Thank you for your extremely fast response and fix.
